name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_FRESHDESK_TOKEN: ${{ secrets.FRESHDESK_TOKEN }}
      BATON_FRESHDESK_DOMAIN: ${{ secrets.FRESHDESK_DOMAIN }}

      # The following parameters are passed to grant/revoke commands
      CONNECTOR_GRANT: 'role:156001705590:assigned:user:156004161664'
      CONNECTOR_ENTITLEMENT: 'role:156001705590:assigned'
      CONNECTOR_PRINCIPAL: '156004161664'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-freshdesk
        run: go build ./cmd/baton-freshdesk
      - name: Run baton-freshdesk
        run: ./baton-freshdesk --api-key=${{ env.BATON_FRESHDESK_TOKEN }} --domain=${{ env.BATON_FRESHDESK_DOMAIN }}

      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin

      - name: Grant entitlement
        run: ./baton-freshdesk --api-key=${{ env.BATON_FRESHDESK_TOKEN }} --domain=${{ env.BATON_FRESHDESK_DOMAIN }} --grant-entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --grant-principal="${{ env.CONNECTOR_PRINCIPAL }}" --grant-principal-type="${{ env.CONNECTOR_PRINCIPAL_TYPE }}"

      - name: Re-sync the data from Freshdesk
        run: ./baton-freshdesk --api-key=${{ env.BATON_FRESHDESK_TOKEN }} --domain=${{ env.BATON_FRESHDESK_DOMAIN }}

      - name: Check grant was granted
        run:
          baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status '.grants[].principal.id.resource == "${{ env.CONNECTOR_PRINCIPAL }}"'

      - name: Revoke grants
        run: ./baton-freshdesk --api-key=${{ env.BATON_FRESHDESK_TOKEN }} --domain=${{ env.BATON_FRESHDESK_DOMAIN }} --revoke-grant="${{ env.CONNECTOR_GRANT }}"


      - name: Re-sync the data from Freshdesk
        run: ./baton-freshdesk --api-key=${{ env.BATON_FRESHDESK_TOKEN }} --domain=${{ env.BATON_FRESHDESK_DOMAIN }}

      - name: Check grant was revoked
        run: ./baton-freshdesk --api-key=${{ env.BATON_FRESHDESK_TOKEN }} --domain=${{ env.BATON_FRESHDESK_DOMAIN }} && baton grants --entitlement="${{ env.CONNECTOR_ENTITLEMENT }}" --output-format=json | jq --exit-status 'if .grants then .grants[]?.principal.id.resource != "${{ env.CONNECTOR_PRINCIPAL }}" else . end'

